//
//  Apparently post is required for Basic Authorization to work...
//
GET {{api_host}}
Authorization: Basic cGZoYW5jaHg6UGxhdGludW0yMDE3LjQ=
###
POST {{api_host}}{{authenticate}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

j_username=pfhanchx&j_password=Platinum2017.4
###

GET {{api_host}}{{root_services}}
Cookie: LtpaToken2=DiRtNSC8R1C6+Ug8yOv8F6uhZwDjeXNwoUfCieQTFGVJd4MfCKYliH3e+b30TXhIwDyuvzZTYwQKFBm/+VI6jRILlWOCzY3qyDdQAQXMDMOnPPjEOEappjuLvNIx1OnvQ+d0NgT0ewFzNbn83bAy3e5amePdoz6rBRmCoEENMWzzCH4svyhnlBbxW4ItR6MEtyaUEP4Pv+lhZsDjRdPjI1GnQnjUUnZRbaNOrXLOn+/85u3lvFFssk+thWZk8eA8FBCKoaMIJT1nuSuZNiS/ej3IC5BMwguZV8BunjaKujYVtdVxVCZvfUR+pj7ts87fQzGE3TTJdYtAPOC1iYKTGIStCGYDzZMm0AfmJ72u+s9vEpTso54p5odqeqgA+23DZIhd5d/209aCCgs4zp4d7/TPdOTBawzeENGZpJcSFw4z3j4RiwAZthCFvEqRZuBAUl5bunjK3fnWxdCAFzrfn9y1794ok1Gqx6lCxDFN6aYnbbBDIY1YfRx+RPcbLl2Wx4lJUnzOrw3/8+FWXoEdFtLh4s4F17MpbRM3zXr0CjzNDj0GMPyDPUFs7czfxe6piK0GpZl0kxwiU04dWlol7BVzdvnmEQqVM+2q20i4Cbpe/AwS8MJsvSbeX6pbymimDL2lZXcmRnFoty10gyIsZP+yZMptgp8wQOG2iBhu5GOnqzljCl4QaWsUUFDhBzZy4qx+IZgxwiX/L2HXoPQhwJwZxIUJdHrGURnalMjIvFaSkWKaxHHDBaD97KqIdQxIKH9w2Sr91x5AJ/08dYHpkQ==; Path=/; Secure; HttpOnly
OSLC-Core-Version: 2.0
Accept: application/rdf+xml

###
GET {{api_host}}/rrc/application-about
Cookie: LtpaToken2=DiRtNSC8R1C6+Ug8yOv8F6uhZwDjeXNwoUfCieQTFGVJd4MfCKYliH3e+b30TXhIwDyuvzZTYwQKFBm/+VI6jRILlWOCzY3qyDdQAQXMDMOnPPjEOEappjuLvNIx1OnvQ+d0NgT0ewFzNbn83bAy3e5amePdoz6rBRmCoEENMWzzCH4svyhnlBbxW4ItR6MEtyaUEP4Pv+lhZsDjRdPjI1GnQnjUUnZRbaNOrXLOn+/85u3lvFFssk+thWZk8eA8FBCKoaMIJT1nuSuZNiS/ej3IC5BMwguZV8BunjaKujYVtdVxVCZvfUR+pj7ts87fQzGE3TTJdYtAPOC1iYKTGIStCGYDzZMm0AfmJ72u+s9vEpTso54p5odqeqgA+23DZIhd5d/209aCCgs4zp4d7/TPdOTBawzeENGZpJcSFw4z3j4RiwAZthCFvEqRZuBAUl5bunjK3fnWxdCAFzrfn9y1794ok1Gqx6lCxDFN6aYnbbBDIY1YfRx+RPcbLl2Wx4lJUnzOrw3/8+FWXoEdFtLh4s4F17MpbRM3zXr0CjzNDj0GMPyDPUFs7czfxe6piK0GpZl0kxwiU04dWlol7BVzdvnmEQqVM+2q20i4Cbpe/AwS8MJsvSbeX6pbymimDL2lZXcmRnFoty10gyIsZP+yZMptgp8wQOG2iBhu5GOnqzljCl4QaWsUUFDhBzZy4qx+IZgxwiX/L2HXoPQhwJwZxIUJdHrGURnalMjIvFaSkWKaxHHDBaD97KqIdQxIKH9w2Sr91x5AJ/08dYHpkQ==; Path=/; Secure; HttpOnly
Cookie: JSESSIONID=0000iphIaMxMW-koJmbigH3ZUj8:455d5119-f8d3-4416-afa2-9b805ce1f004; Path=/; Secure; HttpOnly
OSLC-Core-Version: 2.0
Accept: application/rdf+xml

###
GET {{api_host}}{{catalog}}
Cookie: LtpaToken2=DiRtNSC8R1C6+Ug8yOv8F6uhZwDjeXNwoUfCieQTFGVJd4MfCKYliH3e+b30TXhIwDyuvzZTYwQKFBm/+VI6jRILlWOCzY3qyDdQAQXMDMOnPPjEOEappjuLvNIx1OnvQ+d0NgT0ewFzNbn83bAy3e5amePdoz6rBRmCoEENMWzzCH4svyhnlBbxW4ItR6MEtyaUEP4Pv+lhZsDjRdPjI1GnQnjUUnZRbaNOrXLOn+/85u3lvFFssk+thWZk8eA8FBCKoaMIJT1nuSuZNiS/ej3IC5BMwguZV8BunjaKujYVtdVxVCZvfUR+pj7ts87fQzGE3TTJdYtAPOC1iYKTGIStCGYDzZMm0AfmJ72u+s9vEpTso54p5odqeqgA+23DZIhd5d/209aCCgs4zp4d7/TPdOTBawzeENGZpJcSFw4z3j4RiwAZthCFvEqRZuBAUl5bunjK3fnWxdCAFzrfn9y1794ok1Gqx6lCxDFN6aYnbbBDIY1YfRx+RPcbLl2Wx4lJUnzOrw3/8+FWXoEdFtLh4s4F17MpbRM3zXr0CjzNDj0GMPyDPUFs7czfxe6piK0GpZl0kxwiU04dWlol7BVzdvnmEQqVM+2q20i4Cbpe/AwS8MJsvSbeX6pbymimDL2lZXcmRnFoty10gyIsZP+yZMptgp8wQOG2iBhu5GOnqzljCl4QaWsUUFDhBzZy4qx+IZgxwiX/L2HXoPQhwJwZxIUJdHrGURnalMjIvFaSkWKaxHHDBaD97KqIdQxIKH9w2Sr91x5AJ/08dYHpkQ==; Path=/; Secure; HttpOnly
Cookie: JSESSIONID=0000iphIaMxMW-koJmbigH3ZUj8:455d5119-f8d3-4416-afa2-9b805ce1f004; Path=/; Secure; HttpOnly
OSLC-Core-Version: 2.0
Accept: application/xml

###
GET {{api_host}}{{project_services}}
//Cookie: LtpaToken2=uLK/TWQO3/PfnmC2nHBxtOkxOL4NjfcmOzaOoku219VQeHaMDUTFvgPDDWqw+5FoqXZnCIcB6gaw7+86UjExNfArIf7OMXNGy+9BITK+JGpgERHaDw3kL38GiQHN6tY0x3LOcOFmhtY59c20RzmLDUrhEgRj3fjTQOLfKjnYMVb9v3G2Z/seODdc7DscbHhTvp8/Xoa12BwZ31jC3DghgHM8vQIBsv1BNmNDOZJ6DVwcIRViedpWdPypLHFBZVEqg/haoSEiGdkSCNPE7MC6YDlt79OBInMD/dHBb4P4GnmvwxnUbaF4O6xKCSHfoH+tQpDcBQpDBullzSXNw7VTkFDbPGEZymT5badhlAMHAitAeavffhWmqibx/h/koOT/03Td5EJF5EJMQq4qxfMeIul1p6Bq3oA69+F0MODkrUap5Oo154k9orNUhSJeywUc1FmXjfWYhWybOa07KDRXMpyyfgPSc6AhxAi39jOdpmpL8fEJ7g7yiXElvkMeLV+YHTuPo9myLWu+8Xv+7giu1qmx/5lu/siaZs1nkzJloq+w0MMQrCfiJQS0XBh0UGq+ncJ/4MXjBB/ocIM8skYy5+3gfHaQuoZN29tFKQZEKMBo1qwjWmJQ4jY/7cEnvrCEURu50jWR+SyONpL1xX15uX6cMDTzrFpAp2/5jpDol7BsNm/ubUAUj6liWtFwiWP2PuT86aKI26m5na4Rg5QPyNp3eNvbFhl3ONRLrPS4X/bAGrR7kkVeQXwaCCIkeJ0W4xJLqjEicWkq0CxH1NPLiw==; Path=/; Secure; HttpOnly
//Cookie: JSESSIONID=0000O9A5IhieAncnuLpPzdeyzWG:272b86d1-40eb-45b7-a6cd-531d896225bc; Path=/; Secure; HttpOnly
OSLC-Core-Version: 2.0
Accept: application/xml

###
